/*
 * Miscellaneous extensions, seen in the wild.
 */
"GL_ATI_texture_compression_3dc",
"GL_OES_compressed_ETC2_RGB8_texture",
"GL_OES_compressed_ETC2_RGBA8_texture",
"GL_OES_compressed_ETC2_sRGB8_texture",
"GL_OES_compressed_ETC2_sRGB8_alpha8_texture",
"GL_OES_compressed_EAC_R11_unsigned_texture",
"GL_OES_compressed_EAC_RG11_unsigned_texture",
"GL_ANGLE_lossy_etc_decode",
/*
 * WebGL extensions, Khronos ratified, 2026-08-01.
 * https://registry.khronos.org/webgl/extensions/
 *
 * Note: these have been GL prefixed, with the reasoning that WEBGL is the same
 * as EXT, ARB, etc., justified by its use as a postfix in parameter names.
 */
"GL_WEBGL_compressed_texture_s3tc",
"GL_WEBGL_debug_renderer_info",
"GL_WEBGL_debug_shaders",
"GL_WEBGL_depth_texture",
"GL_WEBGL_draw_buffers",
"GL_WEBGL_lose_context",
/*
 * Khronos community approved.
 */
"GL_WEBGL_blend_func_extended",
"GL_WEBGL_clip_cull_distance",
"GL_WEBGL_color_buffer_float",
"GL_WEBGL_compressed_texture_astc",
"GL_WEBGL_compressed_texture_etc",
"GL_WEBGL_compressed_texture_etc1",
"GL_WEBGL_compressed_texture_pvrtc",
"GL_WEBGL_compressed_texture_s3tc_srgb",
"GL_WEBGL_multi_draw",
"GL_WEBGL_polygon_mode",
"GL_WEBGL_provoking_vertex",
"GL_WEBGL_render_shared_exponent",
"GL_WEBGL_stencil_texturing",
/*
 * Khronos draft.
 */
"GL_WEBGL_blend_equation_advanced_coherent",
"GL_WEBGL_draw_instanced_base_vertex_base_instance",
"GL_WEBGL_multi_draw_instanced_base_vertex_base_instance",
"GL_WEBGL_shader_pixel_local_storage",
/*
 * Khonos proposed.
 */
"GL_EXT_texture_norm16_dom_source",
"GL_WEBGL_debug",
"GL_WEBGL_dynamic_texture",
"GL_WEBGL_video_texture",
"GL_WEBGL_webcodecs_video_frame",
/*
 * Khronos rejected.
 */
"GL_WEBGL_compress_texture",
"GL_WEBGL_compressed_texture_atc",
"GL_WEBGL_debug_shader_precision",
"GL_WEBGL_draw_elements_no_range_check",
"GL_WEBGL_get_buffer_sub_data_async",
"GL_WEBGL_security_sensitive_resources",
"GL_WEBGL_shared_resources",
"GL_WEBGL_subarray_uploads",
"GL_WEBGL_subscribe_uniform",
"GL_WEBGL_texture_from_depth_video",
"GL_WEBGL_texture_multisample",
"GL_WEBGL_texture_source_iframe",
/*
 * From the ANGLE source, 2026-07-30: requestable.
 */
"GL_ANGLE_base_vertex_base_instance",
"GL_ANGLE_base_vertex_base_instance_shader_builtin",
"GL_ANGLE_blob_cache",
"GL_ANGLE_clip_cull_distance",
"GL_ANGLE_compressed_texture_etc",
"GL_ANGLE_copy_texture_3d",
"GL_ANGLE_get_image",
"GL_ANGLE_get_tex_level_parameter",
"GL_ANGLE_logic_op",
"GL_ANGLE_memory_object_flags",
"GL_ANGLE_memory_object_fuchsia",
"GL_ANGLE_memory_size",
"GL_ANGLE_multi_draw",
"GL_ANGLE_multiview_multisample",
"GL_ANGLE_polygon_mode",
"GL_ANGLE_provoking_vertex",
"GL_ANGLE_read_only_depth_stencil_feedback_loops",
"GL_ANGLE_renderability_validation",
"GL_ANGLE_robust_fragment_shader_output",
"GL_ANGLE_semaphore_fuchsia",
"GL_ANGLE_shader_pixel_local_storage",
"GL_ANGLE_shader_pixel_local_storage_coherent",
"GL_ANGLE_stencil_texturing",
"GL_ANGLE_texture_multisample",
"GL_ANGLE_texture_rectangle",
"GL_ANGLE_vulkan_image",
"GL_ANGLE_yuv_internal_format",
"GL_CHROMIUM_color_buffer_float_rgb",
"GL_CHROMIUM_color_buffer_float_rgba",
"GL_CHROMIUM_lose_context",
"GL_NV_read_depth",
/*
 * From the ANGLE source, 2026-07-30: ES only.
 */
"GL_ANGLE_client_arrays",
"GL_ANGLE_explicit_context",
"GL_ANGLE_get_serialized_context_string",
"GL_ANGLE_program_binary_readiness_query",
"GL_ANGLE_program_cache_control",
"GL_ANGLE_relaxed_vertex_attribute_type",
"GL_ANGLE_request_extension",
"GL_ANGLE_rgbx_internal_format",
"GL_ANGLE_robust_client_memory",
"GL_ANGLE_robust_resource_initialization",
"GL_ANGLE_shader_binary",
"GL_ANGLE_webgl_compatibility",
"GL_CHROMIUM_bind_generates_resource",
"GL_CHROMIUM_bind_uniform_location",
"GL_CHROMIUM_copy_compressed_texture",
"GL_CHROMIUM_copy_texture",
